# Generated by Django 5.0.1 on 2024-02-01 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.IntegerField()),
                ('pir1', models.IntegerField()),
                ('pir2', models.IntegerField()),
                ('pir3', models.IntegerField()),
                ('pir4', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading',
            },
        ),
    ]
