# Generated by Django 5.0.1 on 2024-02-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='trigger',
            field=models.IntegerField(null=True),
        ),
    ]
