# Generated by Django 5.0.6 on 2024-07-10 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0002_alter_reading_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntruderAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pir', models.IntegerField(choices=[(1, 'PIR1'), (2, 'PIR2'), (3, 'PIR3'), (4, 'PIR4')], default=1)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'intruder_attempts',
            },
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
