# Generated by Django 5.0.6 on 2024-07-11 03:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0003_intruderattempt_delete_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pir', models.CharField(choices=[('PIR1', 'PIR1'), ('PIR2', 'PIR2'), ('PIR3', 'PIR3'), ('PIR4', 'PIR4')], max_length=10, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
