# Generated by Django 5.0.6 on 2024-07-15 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0004_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alarm',
            },
        ),
    ]
