# Generated by Django 5.0.6 on 2024-07-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_management', '0005_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intruderattempt',
            name='pir',
            field=models.IntegerField(choices=[(1, 'PIR1'), (2, 'PIR2'), (3, 'PIR3'), (4, 'PIR4')]),
        ),
        migrations.AlterField(
            model_name='intruderattempt',
            name='status',
            field=models.IntegerField(),
        ),
    ]
